export const PROJECT_GET_LIST = "PROJECT_GET_LIST";
export const PROJECT_CREATE = "PROJECT_CREATE";
export const PROJECT_UPDATE = "PROJECT_UPDATE";
export const PROJECT_APPLY = "PROJECT_APPLY";
export const PROJECT_APPLY_CANCEL = "PROJECT_APPLY_CANCEL";
