export const SKILL_UPLOAD = "SKILL_UPLOAD";
export const SKILL_GET_LIST = "SKILL_GET_LIST";
export const UNSELECTED_SKILL_REMOVE = "UNSELECTED_SKILL_REMOVE";
export const UNSELECTED_SKILL_ADD = "UNSELECTED_SKILL_ADD";
export const SKILL_ADD = "SKILL_ADD";
export const SKILL_SELECTED = "SKILL_SELECTED";
