export const STUDY_GET_LIST = "STUDY_GET_LIST";
export const STUDY_CREATE = "STUDY_CREATE";
export const STUDY_UPDATE = "STUDY_UPDATE";
export const STUDY_APPLY = "STUDY_APPLY";
export const STUDY_APPLY_CANCEL = "STUDY_APPLY_CANCEL";
export const STUDY_APPLY_ACCEPT = "STUDY_APPLY_ACCEPT";
export const STUDY_APPLY_REJECT = "STUDY_APPLY_REJECT";
