const SKILLS_MODEL = "SKILLS_MODEL";
const USER_MODEL = "USER_MODEL";
const PROJECT_MODEL = "PROJECT_MODEL";
const STUDY_MODEL = "STUDY_MODEL";

module.exports = {
  SKILLS_MODEL,
  USER_MODEL,
  PROJECT_MODEL,
  STUDY_MODEL,
};
